language: r
r:
  - oldrel
  - release
  - devel
jobs:
  include:
    - stage: oldrel
      r: oldrel
      env:
        - CURRENT_STAGE=oldrel
    - stage: release
      r: release
      env:
        - CURRENT_STAGE=release
    - stage: devel
      r: devel
      env:
        - CURRENT_STAGE=devel
#stages:
#  - release
#  - oldrel
#    if: branch = master OR branch = test
#  - devel
#    if: branch = master OR branch = test
sudo: required

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
  -  jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
