language: r
r:
  - oldrel
  - release
  - devel
sudo: required
jobs:
  include:
    stages:
      - name: oldrel
        if: branch = master OR branch = test
      - release
      - name: devel
        if: branch = master OR branch = test

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
  -  jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
