language: r
#r:
#  - oldrel
#  - release
#  - devel
  
jobs:
  include:
    - stage: release
      r: release
      env:
        - CURRENT_STAGE=release  
    - stage: oldrel
      r: oldrel
      if: branch = master OR branch = test
      env:
        - CURRENT_STAGE=oldrel
    - stage: devel
      r: devel
      if: branch = master OR branch = test
      env:
        - CURRENT_STAGE=devel
#stages:
#  - release
#  - oldrel
#    if: branch = master OR branch = test
#  - devel
#    if: branch = master OR branch = test

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
  -  jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
  - echo $TRAVIS_BRANCH
  - echo $CURRENT_STAGE  
  - if [[ $TRAVIS_BRANCH == "test" ]] AND [[ $CURRENT_STAGE == "release" ]]; then bash tests_bash/pxweb.sh ; fi
  - if [[ $TRAVIS_BRANCH == "test" ]] AND [[ $CURRENT_STAGE == "release" ]]; then . PXWEB_ERROR.sh ; fi
  - if [[ $TRAVIS_BRANCH == "test" ]] AND [[ $CURRENT_STAGE == "release" ]]; then cat PXWEB_ERROR.sh ; fi
  - if [[ $TRAVIS_BRANCH == "test" ]] AND [[ $CURRENT_STAGE == "release" ]]; then echo $PXWEB_ERROR ; fi
  - if [[ $TRAVIS_BRANCH == "test" ]] AND [[ $CURRENT_STAGE == "release" ]]; then exit $PXWEB_ERROR ; fi

notifications:
  email:
    on_success: change
    on_failure: change
