language: r
jobs:
  include:
    stages:
      - name: oldrel
        if: branch = master OR branch = test
        r: oldrel
      - name: release
        r: release 
      - name: devel
        if: branch = master OR branch = test
        r: devel

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
  -  jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
